<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Liku" name="TestPackage.RWECohortBuilderAPITest" tests="5" failures="0" timestamp="25 Sep 2019 17:12:16 GMT" time="9.234" errors="1">
  <testcase name="getMyCohorts" time="0.000" classname="TestPackage.RWECohortBuilderAPITest">
    <skipped/>
  </testcase> <!-- getMyCohorts -->
  <testcase name="postCohortAPI" time="0.000" classname="TestPackage.RWECohortBuilderAPITest">
    <skipped/>
  </testcase> <!-- postCohortAPI -->
  <testcase name="commonService" time="9.234" classname="TestPackage.RWECohortBuilderAPITest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at TestPackage.RWECohortBuilderAPITest.commonService(RWECohortBuilderAPITest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- commonService -->
  <testcase name="getCohortLib" time="0.000" classname="TestPackage.RWECohortBuilderAPITest">
    <skipped/>
  </testcase> <!-- getCohortLib -->
  <testcase name="postCohortApproveRequest" time="0.000" classname="TestPackage.RWECohortBuilderAPITest">
    <skipped/>
  </testcase> <!-- postCohortApproveRequest -->
</testsuite> <!-- TestPackage.RWECohortBuilderAPITest -->
